### ISSUE TITLE
[Request] Add config to limit scale upgrades

### ISSUE THREAD

**Issue by EnderGamingFilms** [BuiltBrokenModding/MFFS_Classic#49]
**What It Does** 
Limits the amount of scale upgrades that can be put inside of the force field and interdiction matrix.

**Why**
There is already an implementable scale limit for the custom projection module so I was thinking that it would make more sense to implement that for any block that can use the scale modules.

This would also greatly help server owners that wish to use the mod 😁

**How Does It Work**
In the configuration it will let you you be able to specify the max amount of scale modules that can be put inside of the machine. Another way this can be implemented is to have a map in the config for putting like
```yml
force_field_projector:
    all:
        speed_module: 128
    dome:
        scale_module: 64
interdiction matrix:
    scale_module: 64
```
